[package]
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
name = "livesplit-one-terminal"
version = "0.1.0"
edition = "2018"

[dependencies]
livesplit-core = { git = "https://github.com/LiveSplit/livesplit-core" }
crossterm = "0.12.1"
